### ISSUE TITLE
Error checking module lgsm after container restart

### ISSUE THREAD

**Issue by Severin-S** [jusito/docker-ttt#14]
# Description
When I restart the container it fails to start again with the error noted below.
When recreating the container, it starts fine.

# Steps to reproduce
```sh
docker-compose up-d
# wait until server finished starting
docker restart ttt-server
```
# Config
```yaml
version: '3.3'
services:
  server:
    container_name: ttt-server
    restart: unless-stopped
    image: jusito/docker-ttt:latest
    ports:
      - "27015:27015/tcp"
      - "27015:27015/udp"
    environment:
      - "SERVER_NAME=NAME"
      - "SERVER_PASSWORD=PW"
      - "SERVER_PORT=27015"
      - "WORKSHOP_COLLECTION_ID=COLLECTION_ID"
      - "SERVER_DEFAULT_MAP=ttt_nether"
      - "INSTALL_CSS=true"
      - "TZ=Europe/Berlin"
    volumes:
      - ./data/ttt/:/home/steam/serverfiles/
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
```
# Logs
```
[entrypoint.sh]starting entrypoint.sh
[entrypoint.sh]updating...
[  OK  ] Updating LinuxGSM gmodserver: Selecting repo: GitHub
checking GitHub linuxgsm.sh...OK
checking gmodserver...OK
checking GitHub config _default.cfg...OK
checking GitHub config debian-10.csv...OK
checking GitHub module check.sh...OK
checking GitHub module check_config.sh...OK
checking GitHub module check_deps.sh...OK
checking GitHub module check_executable.sh...OK
checking GitHub module check_glibc.sh...OK
checking GitHub module check_ip.sh...OK
checking GitHub module check_logs.sh...OK
checking GitHub module check_permissions.sh...OK
checking GitHub module check_root.sh...OK
checking GitHub module check_status.sh...OK
checking GitHub module check_steamcmd.sh...OK
checking GitHub module check_system_dir.sh...OK
checking GitHub module check_system_requirements.sh...OK
checking GitHub module check_tmuxception.sh...OK
checking GitHub module check_version.sh...OK
checking GitHub module command_install.sh...OK
checking GitHub module command_start.sh...OK
checking GitHub module command_update_linuxgsm.sh...OK
checking GitHub module core_dl.sh...OK
checking GitHub module core_exit.sh...OK
checking GitHub module core_functions.sh...OK
checking GitHub module core_getopt.sh...OK
checking GitHub module core_legacy.sh...OK
checking GitHub module core_logs.sh...OK
checking GitHub module core_messages.sh...OK
checking GitHub module core_steamcmd.sh...OK
checking GitHub module core_trap.sh...OK
checking GitHub module fix.sh...OK
checking GitHub module fix_steamcmd.sh...OK
checking GitHub module info_distro.sh...OK
checking GitHub module info_game.sh...OK
checking GitHub module install_complete.sh...OK
checking GitHub module install_config.sh...OK
checking GitHub module install_gslt.sh...OK
checking GitHub module install_header.sh...OK
checking GitHub module install_logs.sh...OK
checking GitHub module install_server_dir.sh...OK
checking GitHub module install_server_files.sh...OK
checking GitHub module install_stats.sh...OK
checking GitHub module install_steamcmd.sh...OK
checking GitHub module lgsm...ERROR
rm: cannot remove 'lgsm': Is a directory
removing module lgsm...FAIL
```
