### ISSUE TITLE
Server does not start

### ISSUE THREAD

**Issue by EuleMitKeule** [jusito/docker-ttt#15]
After setting up everything according to the readme, the container stops giving log output with the last message being

`[  OK  ] Starting gmodserver: myservername`

After this the server is unreachable and I can see that the used port (27015) is not being used by any process.

**Comment by EuleMitKeule** [comment]
I tried running the container in `network_mode: host` and bridge, and tried changing the `SERVER_IP` to my server's local IP address, it still is unreachable over local network and the port is not being used.

**Comment by EuleMitKeule** [comment]
```yaml
  ttt:
    <<: *promtail-logging
    image: jusito/docker-ttt:gmod_ttt_debian
    container_name: ttt
    restart: unless-stopped
    network_mode: host
    environment:
      - SERVER_IP="192.168.2.146"
      - SERVER_PORT=27015
      - INSTALL_CSS=true
      - WORKSHOP_COLLECTION_ID=2865833593
      - SERVER_NAME="eulenet"
      - SERVER_PASSWORD="tttonthehills"
      - SERVER_DEFAULT_MAP="ttt_rooftops_2016"
      - SERVER_VOICE_ENABLE=0
      - SERVER_GAMEMODE="terrortown"
    volumes:
      - ${DATA_FOLDER}/ttt/server:/home/steam/serverfiles

**Comment by EuleMitKeule** [comment]
This is my current docker-compose config:
```yaml
  ttt:
    image: jusito/docker-ttt:gmod_ttt_debian
    container_name: ttt
    restart: unless-stopped
    network_mode: host
    environment:
      - SERVER_IP="192.168.2.146"
      - SERVER_PORT=27015
      - INSTALL_CSS=true
      - WORKSHOP_COLLECTION_ID=XXX
      - SERVER_NAME="XXX"
      - SERVER_PASSWORD="XXX"
      - SERVER_DEFAULT_MAP="ttt_rooftops_2016"
      - SERVER_VOICE_ENABLE=0
      - SERVER_GAMEMODE="terrortown"
    volumes:
      - ${DATA_FOLDER}/ttt/server:/home/steam/serverfiles
  ```

**Comment by EuleMitKeule** [comment]
Maybe some of this is relevant.
```
[entrypoint.sh]update / installation done!
[prepareServer.sh]check configurations
[initConfig.sh]Request for replacing hostname to ""XXX"", source is found 1 times
[initConfig.sh]Request for replacing sv_password to ""XXX"", source is found 1 times
[initConfig.sh]Request for replacing sv_voiceenable to "0", source is found 1 times
[prepareServer.sh]force workshop download
[forceWorkshopDownload.sh]processing workshop collection XXXX
[prepareServer.sh]install & mount gamefiles
Server is running, waiting for SIGTERM
[ WARN ] Starting gmodserver: Missing dependencies: distro-infosudo dpkg --add-architecture i386; sudo apt update; sudo apt install distro-info
jq: error (at <stdin>:0): Cannot iterate over null (null)
[  OK  ] Starting gmodserver: Applying steamclient.so sdk64 hardlink fix: Garry's Mod
[  OK  ] Starting gmodserver: Applying steamclient.so sdk32 link fix: Garry's Mod
[  OK  ] Starting gmodserver: myservername
```

**Comment by jusito** [comment]
1. Looks like I need to add a new dependency, but its only needed for some lgsm commands if iam right, so should start.
2. You are using environment array notation, you can only quote "value=key" but if you do value="key" the value will contain the " thats why the example has dictionary notation. So its looking for a map "ttt_rooftops_2006" not ttt_rooftops_2006, server will not start. Same for gamemode, and you dont need to set it should be set already.
3. Setting SERVER_IP can have a negative side effect in docker environment, default 0.0.0.0 is accept from every connection. The old source engine has some issues in virtual environments, e.g. if you are using SERVER_PORT: 27015 but use docker to change it 27016:27015 it will not work. So to confirm, your initial default not setting server_ip / network_mode host was fine.
4. you are missing ports?

try:
```yml
ttt:
    image: jusito/docker-ttt:gmod_ttt_debian
    container_name: ttt
    restart: unless-stopped
    ports:
      - 27015:27015/tcp
      - 27015:27015/udp
    environment:
      - SERVER_PORT=27015
      - INSTALL_CSS=true
      - WORKSHOP_COLLECTION_ID=XXX
      - "SERVER_NAME=XXX"
      - "SERVER_PASSWORD=XXX"
      - "SERVER_DEFAULT_MAP=ttt_rooftops_2016"
      - SERVER_VOICE_ENABLE=0
    volumes:
      - ${DATA_FOLDER}/ttt/server:/home/steam/serverfiles
```
or
try:
```yml
ttt:
    image: jusito/docker-ttt:gmod_ttt_debian
    container_name: ttt
    restart: unless-stopped
    environment:
      SERVER_PORT: "27015"
      INSTALL_CSS: "true"
      WORKSHOP_COLLECTION_ID: "XXX"
      SERVER_NAME: "XXX"
      SERVER_PASSWORD: "XXX"
      SERVER_DEFAULT_MAP: "ttt_rooftops_2016"
      SERVER_VOICE_ENABLE: "0"
    volumes:
      - ${DATA_FOLDER}/ttt/server:/home/steam/serverfiles
```

**Comment by jusito** [comment]
Some time is gone, probably you don't need it anymore?
If you still need it just reopen the issue please.

**Comment by RadekPelikan** [comment]
I would like to reopen this issue, because I'm experiencing similar problems. I'm missing some dependencies and I'm unable to fix it with any other issues closed or opened in this repo. I'm running this machine:
> OS: Debian GNU/Linux 12 (bookworm) x86_64
Host: NUC12WSH-B 90AR00E1-M00080
Kernel: 6.1.0-38-amd64
Uptime: 27 days, 23 hours, 20 mins
Packages: 643 (dpkg)
Shell: bash 5.2.15
Terminal: /dev/pts/0
CPU: 12th Gen Intel i5-1240P (16) @ 4.400GHz
GPU: Intel Alder Lake-P
Memory: 1257MiB / 63879MiB

And this is my docker compose:
```yaml
version: "3.8"

services:
  tttserver:
    image: jusito/docker-ttt:gmod_ttt_debian
    container_name: TTTServer
#    restart: unless-stopped
    ports:
      - "27015:27015/udp"
      - "27015:27015/tcp"
    environment:
      SERVER_PORT: "27015"
      INSTALL_CSS: "true"
      WORKSHOP_COLLECTION_ID: "849865721"
      SERVER_NAME: "###"
      SERVER_PASSWORD: "###"
      SERVER_DEFAULT_MAP: "ttt_lego"
      LGSM_SERVERFILES: "/home/steam/serverfiles/lgsm"
      SERVER_PATH: "/home/steam/serverfiles/lgsm"
    volumes:
      - /mnt/data/gmod:/home/steam/serverfiles
      - ./cfg:/home/steam/serverfiles/garrysmod/cfg
```

Previously there were issues about permissions, because the `steam` user coudln't access the `/mnt/data/gmod/`, but that's been resolved.

The issue that persists is `Missing dependencies: pigz Run: 'sudo dpkg --add-architecture i386; sudo apt update; sudo apt install pigz'`

```logs
TTTServer  | Connecting anonymously to Steam Public...OK
TTTServer  | Waiting for client config...OK
TTTServer  | Waiting for user info...OK
TTTServer  |  Update state (0x5) verifying install, progress: 73.66 (1752875684 / 2379695392)
TTTServer  | Success! App '232330' fully installed.
TTTServer  | Unloading Steam API...OK
TTTServer  | mkdir: cannot create directory ‘/home/steam/logs’: File exists
TTTServer  | Server is running, waiting for SIGTERM
[ WARN ] Starting gmodserver: Missing dependencies: pigz Run: 'sudo dpkg --add-architecture i386; sudo apt update; sudo apt install pigz' as root to install missing dependencies.
[  OK  ] Starting gmodserver: LinuxGSM
```

I think the issue could be resolved by updating `Dockerfile`
