### ISSUE TITLE
Server does not start correctly

### ISSUE THREAD

**Issue by zGatsu** [jusito/docker-ttt#20]
Hi Jusito

There was already a similar issue opened by someone else and I have the same problem. Here is a screenshot of the log (you can ignore the server name :-D ):

![image](https://github.com/jusito/docker-ttt/assets/55385340/62886235-65f6-4553-b07c-63564cb052b2)

At this state, nothing happens and I can not connect to the server. 
That's the docker-compose I use:

```
services:
  ttt:
    image: jusito/docker-ttt:gmod_ttt_debian-develop
    ports:
      - 27015:27015/tcp
      - 27015:27015/udp
    environment:
      INSTALL_CSS: "true"
      INSTALL_HL2: "true"
      SERVER_PORT: 27015
      SERVER_VOICE_ENABLE: 0
      SERVER_MAX_PLAYERS: 10
      SERVER_RCON_PASSWORD: ${PPP}
      WORKSHOP_COLLECTION_ID: 1895900191
      SERVER_NAME: "Test name"
      SERVER_PASSWORD: ${PPP}"
      SERVER_DEFAULT_MAP: "ttt_lttp_kakariko_a4"
    mem_limit: "10g"
    volumes:
      - ./TTTDev1:/home/steam/serverfiles
```

I also tried the answer you gave to the other person with the same problem but that didn't help because I got validation errors since the docker-compose then becomes invalid.

Do you have an idea what could be the problem? 

Thank you in advance. 

Kind regards
