### ISSUE TITLE
Cant connect when running with portainer 

### ISSUE THREAD

**Issue by linde9821** [jusito/docker-ttt#8]
Hi,

i wanted to use your image within my container management tool portainer. 

But I cant get it working. 

```
version: '3.3'

services:

  db:
    image: jusito/docker-ttt:gmod_ttt_debian
    environment:
      SERVER_PORT: "27015"
      INSTALL_CSS: "true"
      WORKSHOP_COLLECTION_ID: "589908800"
      SERVER_NAME: "my-ttt-server"
      SERVER_PASSWORD: "MYSECPAW"
      SERVER_DEFAULT_MAP: "ttt_lttp_kakariko_a4"
      SERVER_RCON_PASSWORD: "MYSECRCPAW"
      SERVER_IP: "172.18.0.12"
    volumes:
      - "ttt_data:/home/steam/serverfiles"
    ports:
      - "27015:27015/tcp"

volumes:
  ttt_data:
    external:
      name: ttt_data
```

It seems like the server starts succesfull but i cannot connect. 

Furthermore i get some strange server logs:

```
 Starting gmodserver: Applying steamclient.so sdk32 fix: Garry's Mod
[ INFO ] Starting gmodserver: Applying steamclient.so sdk32 fix: Garry's Mod
[  OK  ] Starting gmodserver: Applying steamclient.so sdk32 fix: Garry's Mod


fetching GitHub core_logs.sh...OK

[ .... ]
```

And i needed to provide a `SERVER_IP` as otherwise i would get some error message. 

Any thoughts?

**Comment by jusito** [comment]
1. You are only exposing rcon but not game traffic. Rcon needs tcp, gametraffic udp.
2. SERVER_IP is default set to 0.0.0.0 which is the same as "accept connections from everywhere", so there shouldn't be an error message with default value.
3. ttt_lttp_kakariko_a4 got an update, current name is ttt_lttp_kakariko_a5
4. Because your collection has maps in the same collection as content, user will be forced to download each map before the first connection, are you sure you want that?

Converted / fixed your given config and tested it successfuly:
```
docker run -d \
 -p 27015:27015/udp \
 -e SERVER_PORT=27015 \
 -e INSTALL_CSS=true \
 -e WORKSHOP_COLLECTION_ID=589908800 \
 -e SERVER_NAME="my-ttt-server" \
 -e SERVER_PASSWORD="MYSECPAW" \
 -e SERVER_DEFAULT_MAP="ttt_lttp_kakariko_a5" \
 -p 27015:27015/tcp \
 -e SERVER_RCON_PASSWORD="MYSECRCPAW" \
 -v TTTBug:/home/steam/serverfiles \
 jusito/docker-ttt:gmod_ttt_debian
```

So this should work:
```
version: '3.3'

services:

  db:
    image: jusito/docker-ttt:gmod_ttt_debian
    environment:
      SERVER_PORT: "27015"
      INSTALL_CSS: "true"
      WORKSHOP_COLLECTION_ID: "589908800"
      SERVER_NAME: "my-ttt-server"
      SERVER_PASSWORD: "MYSECPAW"
      SERVER_DEFAULT_MAP: "ttt_lttp_kakariko_a5"
      SERVER_RCON_PASSWORD: "MYSECRCPAW"
    volumes:
      - "ttt_data:/home/steam/serverfiles"
    ports:
      - "27015:27015/tcp"
      - "27015:27015/udp"

volumes:
  ttt_data:
    external:
      name: ttt_data
```
